import "./globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";

import Navbar from "./components/navbar";

import Footer from "./components/footer";
import SoftwarePage from "./pages/software_page/page";
import ComparisonPage from "./pages/comparison_page/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></Script>
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
