import "./globals.css";
import { Inter } from "next/font/google";

import Navbar from "./Components/navbar";

import Footer from "./Components/footer";
import ComparisonPage from "./pages/comparison_page/page";
import CategoriesPage from "./pages/categories_page/page";
import SoftwarePage from "./pages/software_page/page";
import WriteReviewPage from "./pages/write_review_page/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
      </head>
      <body className={inter.className}>
        <Navbar />
        <SoftwarePage />
        <Footer />
      </body>
    </html>
  );
}
